"""empty message

Revision ID: 47c84cb89505
Revises: 
Create Date: 2021-02-03 01:53:09.278491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c84cb89505'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('fname_tx', sa.String(length=100), nullable=False),
    sa.Column('lname_tx', sa.String(length=100), nullable=False),
    sa.Column('email_tx', sa.String(length=100), nullable=False),
    sa.Column('ic_card_tx', sa.String(length=20), nullable=False),
    sa.Column('active_fl', sa.Boolean(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('email_tx')
    )
    op.create_table('Permissions',
    sa.Column('permissions_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('permissions_id')
    )
    op.create_table('Practitioner',
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('ic_card_tx', sa.String(length=20), nullable=False),
    sa.Column('doctor_fl', sa.Boolean(), nullable=True),
    sa.Column('active_fl', sa.Boolean(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('practitioner_id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('Provider',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name_tx', sa.String(length=100), nullable=False),
    sa.Column('site_admin_email', sa.String(length=100), nullable=False),
    sa.Column('active_fl', sa.Boolean(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('site_admin_email')
    )
    op.create_table('Vaccine',
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('name_tx', sa.String(length=100), nullable=False),
    sa.Column('doses_required', sa.Integer(), nullable=False),
    sa.Column('description_tx', sa.Text(), nullable=False),
    sa.Column('active_fl', sa.Boolean(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('vaccine_id')
    )
    op.create_table('Appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_by_practitioner_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_fl', sa.Boolean(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.patient_id'], ),
    sa.ForeignKeyConstraint(['scheduled_by_practitioner_id'], ['Practitioner.practitioner_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('Immunization',
    sa.Column('immunization_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('administered_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_fl', sa.Boolean(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.patient_id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['Practitioner.practitioner_id'], ),
    sa.ForeignKeyConstraint(['vaccine_id'], ['Vaccine.vaccine_id'], ),
    sa.PrimaryKeyConstraint('immunization_id')
    )
    op.create_table('RolePermission',
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['Permissions.permissions_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id', 'role_id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('hash_password', sa.Text(), nullable=False),
    sa.Column('security_role', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['security_role'], ['RolePermission.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('RolePermission')
    op.drop_table('Immunization')
    op.drop_table('Appointment')
    op.drop_table('Vaccine')
    op.drop_table('Provider')
    op.drop_table('Practitioner')
    op.drop_table('Permissions')
    op.drop_table('Patient')
    # ### end Alembic commands ###
