"""empty message

Revision ID: bb91f61c4e95
Revises: 657b117f3d7d
Create Date: 2021-02-12 13:21:53.670486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb91f61c4e95'
down_revision = '657b117f3d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vitals',
    sa.Column('vital_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('bp_systolic', sa.String(length=10), nullable=False),
    sa.Column('bp_diastolic', sa.String(length=10), nullable=False),
    sa.Column('body_temp', sa.String(length=10), nullable=False),
    sa.Column('heart_rate', sa.String(length=10), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('active_fl', sa.Boolean(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.patient_id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['Practitioner.practitioner_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['Provider.provider_id'], ),
    sa.PrimaryKeyConstraint('vital_id')
    )
    op.alter_column('Permissions', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('Permissions', 'url',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Permissions', 'url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Permissions', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('Vitals')
    # ### end Alembic commands ###
